apiVersion: v1
kind: Pod
metadata:
  name: pod-raw-restore
  labels:
    name: ubuntu-test
spec:
  containers:
    - image: ubuntu
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command: ["/bin/sleep"]
      args: [ "3600" ]
      name: ubuntu
      volumeDevices:
        - name: vol
          devicePath: /dev/vol # This device path needs to be replaced with the site specific
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: raw-pvc-restore
